title: 디발자 재림이의 블로그
subtitle: 잼로그 since 2024.10

description: >- # this means to ignore newlines until "baseurl:"
  devlopr-jekyll is a beautiful Jekyll Theme Built For Developers, which is optimized for speed and readability.
url: "https://jaerim1102.github.io" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
  - text: Home
    url: /
  - text: About
    url: /about
  - text: Blog
    url: /blog
  - text: Gallery
    url: /gallery
  # - text: Shop
  #   url : /shop
  - text: Contact
    url: /contact

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: 김재림
author_bio: 안녕하세요! 디자인도 되고 개발도 되는 성장하는 디발자 김재림입니당 :D
author_email: "jaerim1102@naver.com"
author_location: South Korea
author_website_url: "https://github.com/jaerim1102"
typewrite-text: 최고의 디발자가 되고 싶은 재림이의 포트폴리오 블로그입니다!
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
  - company_name: 북평초등학교
    company_logo: bukpyeong.png
    company_url: https://dh-bukpyeong.gwe.es.kr/main.do
    designation: 여름방학 특강 미술 보조교사
    description: 2020 여름방학에 진행된 여름방학 방과후 미술 보조교사
    visibility: true
  - company_name: 교육부 국민 서포터즈
    company_logo: edu.png
    company_url: https://www.youtube.com/@%EA%B5%90%EC%9C%A1%EB%B6%80
    designation: 영상 편집 총괄
    description: 대외활동 2020 교육부 국민 서포터즈 영상 편집 총괄
    visibility: true

# Education
author_education_details:
  - college_logo: gwe.png
    college_name: 강원애니고등학교
    college_url: https://anischool.gwe.hs.kr/main.do
    college_degree: 영재 학급 수료
    description: 2016 강원애니고등학교 영재 학급 수료
    visibility: true
  - college_logo: mukho.png
    college_name: 묵호고등학교
    college_url: https://mukho.gwe.hs.kr/main.do?s=mukho
    college_degree: 졸업
    description: 2020 묵호고등학교 졸업
    visibility: true
  - college_logo: dgu.png
    college_name: 동국대학교
    college_url: https://web.dongguk.ac.kr/main
    college_degree: 중퇴
    description: 미술학과 시각디자인 전공
    visibility: true
  - college_logo: kuad.png
    college_name: 계원예술대학교
    college_url: https://www.kaywon.ac.kr/
    college_degree: 재학
    description: 디지털미디어디자인과 프로그래밍 전공
    visibility: true

# Projects
author_project_details:
  - project_thumbnail: weut.png
    project_title: WE;UT
    project_description: 웹사이트 개발 총괄
    project_url: https://jaerim1102.github.io/WE.UT/
    visibility: true
  - project_thumbnail: tving.png
    project_title: TVING 클론 코딩 프로젝트
    project_description: 랜딩 페이지, 검색 페이지, 로그아웃 페이지 개발
    project_url: https://sorry6.netlify.app/
    visibility: true
  - project_thumbnail: jj.png
    project_title: 졸전닷컴
    project_description: 디자인 총괄, 회원가입 페이지, 이용약관 페이지 등
    project_url: https://jjcom.netlify.app/
    visibility: true

# social links
# twitter_username: xplor4r
github_username: jaerim1102
instagram_username: jaaerim
# facebook_username: johndoe
# linkedin_username: johndoe
# behance_username: johndoe
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
# hyvor_talk_website_id: 476

# wakatime username (coding activity)
wakatime_username: jaerim1102

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: jaerim1102@naver.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  - scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  - scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  - scope:
      path: "assets/**"
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

  # jekyll admin is causing issues with github pages, so it's disabled by default
  # - jekyll-admin

# Jekyll Admin Config
# jekyll_admin:
# hidden_links:
#   - posts
#   - pages
#   - staticfiles
#   - datafiles
#   - configuration
# homepage: "posts"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md

destination: ./build
